// Authors levels/NNN.json for a range of levels from the beat sheet and writes docs/levels.md.
//   node tools/author-levels.mjs [from] [to] [--force]
// Existing files are kept unless --force is given, so hand edits made in the editor survive re-runs.
import { build } from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const args = process.argv.slice(2).filter((a) => !a.startsWith('--'));
const force = process.argv.includes('--force');
const from = Number(args[0] || 1),
  to = Number(args[1] || 100);
const DIR = path.resolve('levels');
fs.mkdirSync(DIR, { recursive: true });
fs.mkdirSync(path.resolve('tools/out'), { recursive: true });
await build({
  entryPoints: ['src/engine/author-entry.ts'],
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  outfile: 'tools/out/author.mjs',
  logLevel: 'silent',
});
const a = await import(pathToFileURL(path.resolve('tools/out/author.mjs')).href + '?t=' + Date.now());

const file = (n) => path.join(DIR, String(n).padStart(3, '0') + '.json');
const t0 = Date.now();
let made = 0,
  kept = 0;
for (let n = from; n <= to; n++) {
  if (!force && fs.existsSync(file(n))) {
    kept++;
    continue;
  }
  const r = a.authorLevel(n);
  fs.writeFileSync(file(n), JSON.stringify(r.json, null, 2) + '\n');
  made++;
  const j = r.json;
  console.log(
    `${String(n).padStart(3)} ${j.beat.padEnd(14)} ${j.rows}x${j.cols} c${j.colors} v${j.visibleNext} b${j.beltCap} diff ${j.diff.toFixed(2)} band ${j.band[0]}-${j.band[1]} tries ${r.tries}${r.adjusted.length ? '  [' + r.adjusted.join('; ') + ']' : ''}`
  );
}
console.log(`authored ${made}, kept ${kept}, ${((Date.now() - t0) / 1000).toFixed(1)} s`);

// Report over every file present.
const rows = fs
  .readdirSync(DIR)
  .filter((f) => f.endsWith('.json'))
  .map((f) => JSON.parse(fs.readFileSync(path.join(DIR, f), 'utf8')))
  .sort((x, y) => x.n - y.n)
  .map((j) => {
    const lv = a.levelFromJson(j);
    return `| ${j.n} | ${j.beat} | ${j.rows}×${j.cols} | ${j.colors} | ${lv.diners.length} | ${j.visibleNext} | ${j.beltCap} | ${lv.mechs.join(', ') || '-'} | ${(j.diff * 100).toFixed(0)}% | ${(j.band[0] * 100).toFixed(0)}–${(j.band[1] * 100).toFixed(0)}% |`;
  });
const md = `# Authored levels

Generated by \`node tools/author-levels.mjs\` from the beat sheet in \`src/engine/author.ts\`. Each row is a file in \`levels/\`. The fail rate is measured with 200 runs of the noisy solver at authoring time and re-checked in CI (\`tests/authored.test.ts\`), which also proves solvability. Edit a level in the in-game editor (dev panel), export it, and drop the JSON over the file; re-running the tool keeps existing files unless \`--force\` is given.

| Level | Beat | Grid | Colours | Diners | Window | Belt | Mechanics | Fail rate | Band |
| ----- | ---- | ---- | ------- | ------ | ------ | ---- | --------- | --------- | ---- |
${rows.join('\n')}
`;
fs.writeFileSync(path.resolve('docs/levels.md'), md);
console.log('wrote docs/levels.md');
